"use client";

import { useEffect } from "react";
import { isDesktopApp } from "@/lib/desktop";
import { setWaitingWorker, wasUpdateRequested } from "@/lib/pwa";

/**
 * Registers /sw.js (generated by scripts/build-sw.mjs) in production only:
 * skipped in dev so it never fights with Fast Refresh, and skipped inside the
 * Tauri desktop app, which serves the static export from disk and has nothing
 * to cache. Renders nothing; it wires the registration into lib/pwa so the
 * update banner can react to it, and asks the worker to warm every tool page
 * into the cache once the page is idle.
 */
export function ServiceWorkerRegister() {
  useEffect(() => {
    if (process.env.NODE_ENV !== "production") return;
    if (typeof window === "undefined" || !("serviceWorker" in navigator) || isDesktopApp()) return;

    const onControllerChange = () => {
      // Only after the user clicked "Update": the first install also fires this.
      if (wasUpdateRequested()) window.location.reload();
    };
    navigator.serviceWorker.addEventListener("controllerchange", onControllerChange);

    let cancelled = false;
    let cleanupVisibility: (() => void) | undefined;

    navigator.serviceWorker
      .register("/sw.js")
      .then((registration) => {
        if (cancelled) return;

        const trackInstalling = (worker: ServiceWorker | null) => {
          if (!worker) return;
          worker.addEventListener("statechange", () => {
            if (worker.state === "installed" && navigator.serviceWorker.controller) setWaitingWorker(worker);
          });
        };

        if (registration.waiting && navigator.serviceWorker.controller) setWaitingWorker(registration.waiting);
        trackInstalling(registration.installing);
        registration.addEventListener("updatefound", () => trackInstalling(registration.installing));

        const onVisible = () => {
          if (document.visibilityState === "visible") registration.update().catch(() => {});
        };
        document.addEventListener("visibilitychange", onVisible);
        cleanupVisibility = () => document.removeEventListener("visibilitychange", onVisible);

        return navigator.serviceWorker.ready;
      })
      .then((ready) => {
        if (cancelled || !ready?.active) return;
        // Warm the cache for offline use, but never on a metered connection
        // the user asked to keep light, and only once the page has settled.
        const connection = (navigator as Navigator & { connection?: { saveData?: boolean } }).connection;
        if (connection?.saveData) return;
        const warm = () => ready.active?.postMessage("WARM_CACHE");
        if ("requestIdleCallback" in window) window.requestIdleCallback(warm, { timeout: 10_000 });
        else setTimeout(warm, 3_000);
      })
      .catch(() => {
        // Registration can fail (unsupported browser, private mode, blocked
        // storage). The app works without offline support in that case.
      });

    return () => {
      cancelled = true;
      cleanupVisibility?.();
      navigator.serviceWorker.removeEventListener("controllerchange", onControllerChange);
    };
  }, []);

  return null;
}
