/**
 * Command cheatsheet: a static, curated list of terminal commands grouped by
 * tool or stack, each with a one-line explanation. Search is local and
 * synchronous; nothing is fetched or executed.
 */

export type CommandStack = "Git & GitHub" | "Shell & OS" | "JavaScript" | "Frameworks" | "Python" | "More languages" | "Mobile" | "Infra & Data" | "Troubleshooting";

export type CommandPlatform = "macOS" | "Linux" | "Windows";

export interface CommandEntry {
  cmd: string;
  description: string;
  /** Destroys work or data, or kills processes. Shown with a warning badge. */
  danger?: boolean;
  /** Only works on this OS. Omitted when the command is cross-platform or Unix-wide. */
  platform?: CommandPlatform;
  /** Extra search terms that appear in neither the command nor the description. */
  keywords?: string[];
}

export interface CommandSection {
  id: string;
  title: string;
  stack: CommandStack;
  /** Search terms that apply to every command in the section. */
  keywords?: string[];
  /** Applies to every entry that does not set its own. */
  platform?: CommandPlatform;
  entries: CommandEntry[];
}

export const COMMAND_STACKS: CommandStack[] = ["Git & GitHub", "Shell & OS", "JavaScript", "Frameworks", "Python", "More languages", "Mobile", "Infra & Data", "Troubleshooting"];

/** Placeholders such as <pid>, <file> or <owner/repo> that the user replaces before running. */
export const PLACEHOLDER_RE = /(<[A-Za-z0-9_.:/@-]+>)/;

const c = (cmd: string, description: string, extra: Omit<CommandEntry, "cmd" | "description"> = {}): CommandEntry => ({ cmd, description, ...extra });
const danger = { danger: true } as const;
const mac = { platform: "macOS" } as const;
const linux = { platform: "Linux" } as const;
const windows = { platform: "Windows" } as const;

export const COMMAND_SECTIONS: CommandSection[] = [
  // ---- Git & GitHub
  {
    id: "git",
    title: "Git: everyday",
    stack: "Git & GitHub",
    keywords: ["git", "vcs", "version control"],
    entries: [
      c("git status", "Show changed, staged and untracked files"),
      c("git add -p", "Stage changes hunk by hunk, interactively", { keywords: ["partial", "patch"] }),
      c('git commit -m "<message>"', "Commit staged changes with a message"),
      c("git diff", "Show unstaged changes"),
      c("git diff --staged", "Show what is about to be committed", { keywords: ["cached"] }),
      c("git diff main...HEAD", "Show everything changed since the branch left main"),
      c("git diff --stat", "Summarise changes per file"),
      c("git pull --rebase", "Pull without creating a merge commit"),
      c("git push -u origin HEAD", "Push the current branch and set its upstream"),
      c("git clone --depth 1 <url>", "Fast clone with only the latest commit", { keywords: ["shallow"] }),
      c("git switch -c <branch>", "Create a branch and switch to it", { keywords: ["checkout", "new branch"] }),
      c("git switch -", "Jump back to the previous branch"),
      c('git stash push -m "<message>"', "Shelve uncommitted work with a label", { keywords: ["save"] }),
      c("git stash list", "List stashes"),
      c("git stash pop", "Restore the latest stash and remove it"),
      c("git stash apply stash@{1}", "Restore a specific stash and keep it"),
      c("git add .", "Stage every change in the current folder"),
      c('git commit -am "<message>"', "Stage tracked files and commit in one step"),
      c("git log --oneline -10", "Last ten commits, one line each"),
      c("git branch --show-current", "Name of the current branch"),
      c("git fetch origin", "Download remote changes without touching your files"),
      c("git merge <branch>", "Merge a branch into the current one"),
      c("git diff --name-only main", "Only the names of files that differ from main"),
      c("git stash -u", "Stash including untracked files"),
      c('git grep -n "<text>"', "Search tracked files, fast and without node_modules"),
    ],
  },
  {
    id: "git-undo",
    title: "Git: undo & fix",
    stack: "Git & GitHub",
    keywords: ["git", "undo", "revert", "mistake", "fix"],
    entries: [
      c("git restore <file>", "Discard unstaged changes in a file", { danger: true, keywords: ["checkout", "discard"] }),
      c("git restore --staged <file>", "Unstage a file but keep the changes", { keywords: ["unstage", "reset"] }),
      c("git commit --amend --no-edit", "Add staged changes to the last commit"),
      c('git commit --amend -m "<message>"', "Rewrite the last commit message", { keywords: ["rename", "typo"] }),
      c("git reset --soft HEAD~1", "Undo the last commit, keep its changes staged", { keywords: ["uncommit"] }),
      c("git reset HEAD~1", "Undo the last commit, keep its changes unstaged"),
      c("git reset --hard HEAD", "Throw away every uncommitted change", danger),
      c("git reset --hard origin/main", "Make the branch exactly match the remote", danger),
      c("git revert <sha>", "Create a new commit that undoes an old one (safe on shared branches)"),
      c("git checkout <sha> -- <file>", "Restore one file from an older commit"),
      c("git reflog", "Every position HEAD has been at, to recover lost commits", { keywords: ["recover", "lost", "deleted branch"] }),
      c("git clean -nd", "Preview which untracked files would be deleted", { keywords: ["dry run"] }),
      c("git clean -fd", "Delete untracked files and folders", danger),
      c("git rm --cached <file>", "Stop tracking a file but keep it on disk", { keywords: ["gitignore", "untrack"] }),
      c("git merge --abort", "Cancel a merge that has conflicts"),
      c("git rebase --abort", "Cancel a rebase and go back to where you started"),
      c("git checkout --theirs <file>", "Resolve a conflict by taking the incoming version (--ours keeps yours)", { keywords: ["conflict", "merge"] }),
      c("git rm -r --cached . && git add .", "Re-apply .gitignore to files that are already tracked", { keywords: ["gitignore", "ignored"] }),
      c("git stash drop", "Delete the latest stash", danger),
      c("git update-index --chmod=+x <file>", "Mark a file executable in git, handy on Windows"),
      c("git reset --merge", "Back out of a half-finished merge or stash pop"),
    ],
  },
  {
    id: "git-history",
    title: "Git: branches & history",
    stack: "Git & GitHub",
    keywords: ["git", "branch", "history", "log"],
    entries: [
      c("git log --oneline --graph --all", "Compact commit tree across every branch"),
      c("git log -p <file>", "Full change history of one file"),
      c('git log -S "<text>"', "Find commits that added or removed some text", { keywords: ["pickaxe", "search"] }),
      c('git log --author="<name>" --since="2 weeks ago"', "Filter history by author and date"),
      c("git show <sha>", "Show one commit's message and diff"),
      c("git blame -L 10,20 <file>", "Who last changed lines 10 to 20", { keywords: ["annotate"] }),
      c("git bisect start", "Binary-search commits to find the one that broke something", { keywords: ["regression"] }),
      c("git shortlog -sn", "Contributors ranked by commit count"),
      c("git branch -a", "List local and remote branches"),
      c("git branch -m <new-name>", "Rename the current branch"),
      c("git branch -d <branch>", "Delete a merged local branch"),
      c("git branch -D <branch>", "Force-delete a local branch, merged or not", danger),
      c("git push origin --delete <branch>", "Delete a remote branch"),
      c("git branch --merged main | grep -v main | xargs git branch -d", "Delete every local branch already merged into main", { keywords: ["cleanup"] }),
      c("git fetch --prune", "Update remotes and drop branches deleted on the server"),
      c("git rebase main", "Replay your branch on top of the latest main"),
      c("git rebase -i HEAD~3", "Edit, squash or reorder the last three commits", { keywords: ["squash", "interactive"] }),
      c("git cherry-pick <sha>", "Copy one commit onto the current branch"),
      c("git commit --fixup <sha>", "Record a fix for an older commit; squash it later with rebase --autosquash"),
      c("git rebase -i --autosquash main", "Fold fixup commits into the commits they fix"),
      c("git push --force-with-lease", "Force push, but refuse if someone else pushed in the meantime", { keywords: ["force"] }),
      c("git worktree add ../<folder> <branch>", "Check out a second branch in another folder at the same time"),
      c('git tag -a v1.0.0 -m "v1.0.0"', "Create an annotated release tag", { keywords: ["release", "version"] }),
      c("git push --tags", "Push tags to the remote"),
      c("git remote -v", "Show remote URLs"),
      c("git remote set-url origin <url>", "Point origin at a new URL", { keywords: ["ssh", "https"] }),
      c("git submodule update --init --recursive", "Fetch and check out all submodules"),
      c("git log main..HEAD --oneline", "Commits on your branch that are not on main"),
      c("git log --follow -p <file>", "History of a file, including before it was renamed"),
      c("git show <sha>:<file>", "A file's content at a specific commit"),
      c('git lfs track "*.psd"', "Store large binary files with Git LFS"),
      c("git sparse-checkout set <dir>", "Check out only some folders of a huge repo", { keywords: ["monorepo"] }),
      c("git count-objects -vH", "How much space the repository takes"),
      c("git gc --prune=now", "Compact the repository and drop unreachable objects"),
    ],
  },
  {
    id: "git-config",
    title: "Git: config",
    stack: "Git & GitHub",
    keywords: ["git", "config", "settings", "setup"],
    entries: [
      c('git config --global user.name "<name>"', "Set your commit author name"),
      c('git config --global user.email "<email>"', "Set your commit author email"),
      c("git config --global init.defaultBranch main", "Use main for new repositories"),
      c("git config --global pull.rebase true", "Rebase instead of merge on every pull"),
      c("git config --global push.autoSetupRemote true", "First push creates the upstream automatically"),
      c("git config --global rerere.enabled true", "Remember how you resolved a conflict and reuse it"),
      c('git config --global core.editor "code --wait"', "Use VS Code for commit messages and rebases"),
      c("git config --global alias.st status", "Create a shortcut: git st", { keywords: ["alias"] }),
      c("git config --list --show-origin", "Every setting and the file it comes from"),
      c("git config --global fetch.prune true", "Always drop deleted remote branches on fetch"),
      c("git config --global core.autocrlf input", "Normalise Windows line endings on commit", { keywords: ["crlf", "line endings"] }),
      c("git config core.fileMode false", "Ignore permission-only changes in this repo"),
      c("git config --global diff.algorithm histogram", "Clearer diffs when code moves around"),
      c("git config --global commit.gpgsign true", "Sign every commit"),
    ],
  },
  {
    id: "github-cli",
    title: "GitHub CLI (gh)",
    stack: "Git & GitHub",
    keywords: ["github", "gh", "cli", "pull request", "pr"],
    entries: [
      c("gh auth login", "Sign in to GitHub from the terminal"),
      c("gh auth status", "Show which account and scopes are active"),
      c("gh repo create <name> --private --source=. --push", "Create a GitHub repo from the current folder and push it"),
      c("gh repo clone <owner/repo>", "Clone a repository"),
      c("gh repo fork --clone", "Fork the current repo and clone your fork"),
      c("gh browse", "Open the current repo in the browser"),
      c("gh pr create --fill", "Open a PR using your commit messages as title and body"),
      c("gh pr create --draft", "Open a draft PR"),
      c("gh pr list", "List open pull requests"),
      c("gh pr status", "Your PRs, review requests and their checks"),
      c("gh pr checkout <number>", "Check out a PR locally to test it"),
      c("gh pr diff", "Show the current PR's diff"),
      c("gh pr checks --watch", "Watch the PR's CI checks until they finish"),
      c("gh pr review <number> --approve", "Approve a pull request"),
      c("gh pr merge --squash --delete-branch", "Squash-merge and delete the branch"),
      c("gh issue create", "Create an issue interactively"),
      c("gh issue list --assignee @me", "Issues assigned to you"),
      c("gh run list", "Recent GitHub Actions runs", { keywords: ["actions", "ci"] }),
      c("gh run watch", "Follow a running workflow live", { keywords: ["actions", "ci"] }),
      c("gh run view --log-failed", "Show only the logs of the failed steps", { keywords: ["actions", "ci"] }),
      c("gh run rerun --failed", "Rerun only the failed jobs", { keywords: ["actions", "ci"] }),
      c("gh workflow run <workflow>", "Trigger a workflow_dispatch workflow", { keywords: ["actions"] }),
      c("gh release create v1.0.0 --generate-notes", "Publish a release with automatic notes"),
      c("gh secret set <NAME>", "Add or update a repository secret", { keywords: ["actions", "env"] }),
      c("gh gist create <file>", "Share a file as a gist"),
      c("gh api repos/{owner}/{repo}", "Call any GitHub REST endpoint with your auth"),
      c("gh pr view --web", "Open the current branch's PR in the browser"),
      c("gh pr edit --add-reviewer <user>", "Request a review"),
      c("gh repo sync", "Bring your fork up to date with upstream"),
      c('gh search code "<text>" --owner <org>', "Search code across an organisation"),
      c("act -j <job>", "Run a GitHub Actions job locally in Docker (nektos/act)", { keywords: ["actions", "ci", "local"] }),
    ],
  },

  // ---- Shell & OS
  {
    id: "files",
    title: "Files & search",
    stack: "Shell & OS",
    keywords: ["shell", "terminal", "bash", "zsh", "linux", "unix", "files"],
    entries: [
      c("ls -lah", "List files with sizes, permissions and hidden files"),
      c("tree -L 2 -I node_modules", "Folder tree two levels deep, skipping node_modules"),
      c('grep -rn "<text>" .', "Search text in every file, with line numbers"),
      c('rg "<text>"', "Same search, much faster, respects .gitignore (ripgrep)"),
      c('rg -l "<text>" -g "*.ts"', "Only list TypeScript files that contain the text"),
      c('find . -name "*.log"', "Find files by name pattern"),
      c("find . -type f -size +100M", "Find files larger than 100 MB"),
      c('find . -name "node_modules" -type d -prune -exec rm -rf {} +', "Delete every node_modules folder below here", { danger: true, keywords: ["disk space", "clean"] }),
      c("du -sh * | sort -h", "Size of each item here, smallest to largest", { keywords: ["disk", "space"] }),
      c("df -h", "Free space on each disk"),
      c("tail -f <file>", "Follow a log file as it grows"),
      c("tail -n 100 <file>", "Last 100 lines"),
      c("head -n 20 <file>", "First 20 lines"),
      c("less <file>", "Page through a large file (/ to search, q to quit)"),
      c("wc -l <file>", "Count lines"),
      c("sort <file> | uniq -c | sort -rn", "Count duplicate lines, most frequent first"),
      c("diff -u <a> <b>", "Unified diff of two files"),
      c("mkdir -p a/b/c", "Create nested folders in one go"),
      c("cp -r <src> <dest>", "Copy a folder recursively"),
      c("rm -rf <dir>", "Delete a folder and everything in it, no undo", danger),
      c("ln -s <target> <link>", "Create a symbolic link"),
      c("chmod +x <file>", "Make a script executable"),
      c("chmod 600 ~/.ssh/id_ed25519", "Lock a private key down to your user only"),
      c("chown -R <user>:<group> <dir>", "Change owner of a folder recursively"),
      c("tar -czf out.tar.gz <dir>", "Compress a folder to .tar.gz"),
      c("tar -xzf <file>.tar.gz", "Extract a .tar.gz archive"),
      c("zip -r out.zip <dir>", "Zip a folder"),
      c("unzip <file>.zip -d <dir>", "Unzip into a folder"),
      c("sed -i '' 's/old/new/g' <file>", "Find and replace in place; on Linux drop the ''", mac),
      c("jq '.' <file>.json", "Pretty-print JSON", { keywords: ["json"] }),
      c("jq '.items[] | .name' <file>.json", "Pull one field out of every array item", { keywords: ["json"] }),
      c("pwd", "Print the current folder"),
      c("touch <file>", "Create an empty file or update its timestamp"),
      c("mv <old> <new>", "Move or rename a file"),
      c("file <file>", "Detect what kind of file something is"),
      c("find . -type f -mtime -1", "Files changed in the last 24 hours"),
      c("fd <pattern>", "Friendlier, faster find that respects .gitignore"),
      c("fzf", "Fuzzy-pick a file interactively; pairs well with Ctrl+R"),
      c("bat <file>", "cat with syntax highlighting and line numbers"),
    ],
  },
  {
    id: "processes",
    title: "Processes & ports",
    stack: "Shell & OS",
    keywords: ["process", "port", "kill", "pid", "address already in use", "eaddrinuse"],
    entries: [
      c("lsof -i :<port>", "Which process is using a port"),
      c("lsof -ti :<port> | xargs kill -9", "Kill whatever is using a port", danger),
      c("lsof -iTCP -sTCP:LISTEN -n -P", "Every port that is listening", mac),
      c("ss -tulpn", "Every listening port and its process", linux),
      c("netstat -ano | findstr :<port>", "Which PID is using a port", windows),
      c("taskkill /PID <pid> /F", "Force-stop a process", { ...danger, ...windows }),
      c("npx kill-port <port>", "Free a port on any OS"),
      c("kill <pid>", "Ask a process to stop"),
      c("kill -9 <pid>", "Force-stop a process immediately", danger),
      c("pkill -f <name>", "Kill every process whose command line matches", danger),
      c("ps aux | grep <name>", "Find running processes by name"),
      c("htop", "Interactive CPU and memory monitor (top if not installed)"),
      c("time <command>", "Measure how long a command takes"),
      c("nohup <command> &", "Keep a command running after you close the terminal"),
      c("jobs", "Background jobs in this shell; fg brings one back, bg resumes it"),
      c("systemctl status <service>", "Status of a service", linux),
      c("journalctl -u <service> -f", "Follow a service's logs", linux),
      c("top -o cpu", "Processes sorted by CPU", mac),
      c("uptime", "How long the machine has been up, and its load"),
    ],
  },
  {
    id: "network",
    title: "Networking & SSH",
    stack: "Shell & OS",
    keywords: ["network", "http", "dns", "ssh", "curl", "server"],
    entries: [
      c("curl -I <url>", "Fetch only the response headers"),
      c("curl -L <url>", "Follow redirects"),
      c("curl -sS <url> | jq", "Fetch JSON and pretty-print it"),
      c("curl -X POST <url> -H \"Content-Type: application/json\" -d '{\"a\":1}'", "Send a JSON POST request", { keywords: ["api"] }),
      c('curl -o /dev/null -s -w "%{http_code} %{time_total}s\\n" <url>', "Only the status code and total time"),
      c("curl -o <file> <url>", "Download a file"),
      c("ping <host>", "Is the host reachable, and how fast"),
      c("dig <domain>", "DNS lookup"),
      c("dig +short <domain> TXT", "Just the TXT records (SPF, verification tokens)"),
      c("nslookup <domain>", "DNS lookup, available everywhere including Windows"),
      c("traceroute <host>", "Every hop on the way to a host"),
      c("nc -zv <host> <port>", "Check whether a TCP port is open"),
      c("ipconfig getifaddr en0", "Your local IP address", { ...mac, keywords: ["lan", "ip"] }),
      c("curl ifconfig.me", "Your public IP address"),
      c("ssh <user>@<host>", "Log in to a remote machine"),
      c("ssh -i <key>.pem <user>@<host>", "Log in with a specific key (AWS, GCP)"),
      c("ssh -L 5432:localhost:5432 <user>@<host>", "Tunnel a remote port to localhost", { keywords: ["port forward", "tunnel"] }),
      c('ssh-keygen -t ed25519 -C "<email>"', "Create a new SSH key pair"),
      c("ssh-copy-id <user>@<host>", "Install your public key on a server"),
      c("ssh-add ~/.ssh/id_ed25519", "Load a key into the SSH agent"),
      c("ssh -T git@github.com", "Test your GitHub SSH key"),
      c("scp <file> <user>@<host>:<path>", "Copy a file to a server"),
      c("rsync -avz --progress <src>/ <user>@<host>:<path>", "Sync a folder, copying only what changed"),
      c("openssl s_client -connect <host>:443 -servername <host>", "Inspect a server's TLS certificate", { keywords: ["ssl", "https"] }),
      c('curl -H "Authorization: Bearer <token>" <url>', "Call an API with a bearer token", { keywords: ["auth", "jwt"] }),
      c('curl -F "file=@<path>" <url>', "Upload a file as multipart form data"),
      c("http POST <url> name=value", "Friendlier requests with JSON by default (HTTPie)"),
      c("whois <domain>", "Registrar and expiry date of a domain"),
      c("ssh -J <jump-host> <user>@<host>", "Connect through a bastion host", { keywords: ["jump", "proxy"] }),
      c("ssh-keygen -R <host>", "Forget a stale host key; fixes REMOTE HOST IDENTIFICATION HAS CHANGED"),
    ],
  },
  {
    id: "shell-tricks",
    title: "Shell tricks",
    stack: "Shell & OS",
    keywords: ["shell", "bash", "zsh", "terminal", "shortcut"],
    entries: [
      c("Ctrl+R", "Search your command history as you type"),
      c("!!", "Repeat the last command; sudo !! reruns it as root"),
      c("cd -", "Go back to the previous folder"),
      c("Ctrl+A / Ctrl+E", "Jump to the start / end of the line"),
      c("Ctrl+U / Ctrl+K", "Delete to the start / end of the line"),
      c("Ctrl+L", "Clear the screen"),
      c("<cmd1> && <cmd2>", "Run the second command only if the first succeeds"),
      c("<cmd1> || <cmd2>", "Run the second command only if the first fails"),
      c("<cmd> > out.txt 2>&1", "Save output and errors to one file", { keywords: ["redirect", "stderr"] }),
      c("<cmd> | tee out.txt", "Show output and save it at the same time"),
      c("<cmd> &", "Run a command in the background"),
      c('alias gs="git status"', "Create a shortcut; add it to ~/.zshrc to keep it"),
      c("source ~/.zshrc", "Reload your shell config without restarting"),
      c("export <NAME>=<value>", "Set an environment variable for this session", { keywords: ["env"] }),
      c("echo $PATH", "Show where the shell looks for programs"),
      c("which <command>", "Which binary will run for a command"),
      c("history | grep <text>", "Find a command you ran before"),
      c("watch -n 2 <command>", "Rerun a command every two seconds (brew install watch on macOS)"),
      c("tldr <command>", "Short practical examples for a command (npx tldr works too)", { keywords: ["man", "help"] }),
      c("mkdir <dir> && cd $_", "Create a folder and step into it"),
      c("Ctrl+W", "Delete the word before the cursor"),
      c("!$", "Last argument of the previous command, e.g. mkdir x && cd !$"),
      c("echo $?", "Exit code of the last command (0 means success)"),
      c("printenv", "Every environment variable", { keywords: ["env"] }),
      c('for f in *.png; do echo "$f"; done', "Loop over files"),
      c("clear", "Clear the screen"),
    ],
  },
  {
    id: "macos",
    title: "macOS & Homebrew",
    stack: "Shell & OS",
    platform: "macOS",
    keywords: ["mac", "macos", "brew", "homebrew", "apple"],
    entries: [
      c("brew install <formula>", "Install a command-line tool"),
      c("brew install --cask <app>", "Install a desktop app"),
      c("brew upgrade", "Upgrade everything installed with Homebrew"),
      c("brew cleanup", "Delete old versions and free disk space"),
      c("brew services start <service>", "Run a service such as postgresql or redis in the background"),
      c("brew doctor", "Diagnose Homebrew problems"),
      c("xcode-select --install", "Install the Command Line Tools (git, make, clang)"),
      c("open .", "Open the current folder in Finder"),
      c("code .", "Open the current folder in VS Code"),
      c("pbcopy < <file>", "Copy a file's contents to the clipboard"),
      c("pbpaste > <file>", "Write the clipboard to a file"),
      c("caffeinate -d", "Keep the display awake until you press Ctrl+C"),
      c("sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder", "Flush the DNS cache"),
      c("Cmd+Shift+.", "Show or hide hidden files in Finder"),
      c("sw_vers", "macOS version"),
      c("brew outdated", "Installed formulae with newer versions"),
      c("brew bundle dump", "Save everything you installed to a Brewfile"),
      c("brew bundle", "Install everything listed in a Brewfile (new machine setup)"),
      c('open -a "<app>" <file>', "Open a file with a specific app"),
      c('mdfind "<name>"', "Spotlight search from the terminal"),
      c("xattr -cr /Applications/<app>.app", "Clear quarantine; fixes \"app is damaged and can't be opened\""),
      c("screencapture -i shot.png", "Interactive screenshot straight to a file"),
      c("npm run build && say done", "Hear when a long command finishes"),
    ],
  },

  {
    id: "text-processing",
    title: "Text & data processing",
    stack: "Shell & OS",
    keywords: ["text", "csv", "awk", "sed", "grep", "pipe", "encode"],
    entries: [
      c("awk '{print $1}' <file>", "Print the first column of each line"),
      c("awk -F, '{sum += $3} END {print sum}' <file>.csv", "Sum a CSV column"),
      c("cut -d, -f1,3 <file>.csv", "Pick columns 1 and 3"),
      c("sed -n '10,20p' <file>", "Print lines 10 to 20"),
      c('grep -v "<text>" <file>', "Lines that do not match"),
      c('grep -c "<text>" <file>', "Count matching lines"),
      c('grep -E "error|warn" <file>', "Lines matching any of several patterns"),
      c("cat <file> | xargs -n1 <command>", "Run a command once per input line"),
      c("tr '[:upper:]' '[:lower:]' < <file>", "Lowercase text"),
      c("column -t -s, <file>.csv", "Show a CSV as an aligned table"),
      c("paste -sd, <file>", "Join all lines with commas"),
      c("jq -r '.[] | [.id, .name] | @csv' <file>.json", "JSON array to CSV", { keywords: ["json"] }),
      c("yq '.services' <file>.yaml", "Query YAML the way jq queries JSON"),
      c("date +%s", "Current Unix timestamp", { keywords: ["epoch", "time"] }),
      c("date -u +%Y-%m-%dT%H:%M:%SZ", "Current time in ISO 8601 UTC"),
      c("uuidgen", "Generate a UUID", { keywords: ["id", "guid"] }),
      c('echo -n "<text>" | base64', "Base64-encode text"),
      c('echo "<base64>" | base64 --decode', "Decode Base64 (works on macOS and Linux)"),
      c('echo -n "<text>" | shasum -a 256', "SHA-256 of a string", { keywords: ["hash"] }),
      c("iconv -f latin1 -t utf-8 <file> > out.txt", "Convert a file's encoding"),
      c("dos2unix <file>", "Convert Windows line endings to Unix"),
    ],
  },
  {
    id: "linux-server",
    title: "Linux server",
    stack: "Shell & OS",
    platform: "Linux",
    keywords: ["linux", "server", "ubuntu", "debian", "vps", "sysadmin"],
    entries: [
      c("sudo apt update && sudo apt upgrade -y", "Update package lists and upgrade everything"),
      c("sudo apt install <pkg>", "Install a package"),
      c("cat /etc/os-release", "Distribution and version"),
      c("free -h", "Memory and swap usage"),
      c("lsblk", "Disks and partitions"),
      c("whoami && id", "Current user and their groups"),
      c("sudo -u <user> <command>", "Run a command as another user"),
      c("sudo adduser <user>", "Create a user"),
      c("sudo usermod -aG docker <user>", "Let a user run docker without sudo (log out and back in)"),
      c("sudo systemctl restart <service>", "Restart a service"),
      c("sudo systemctl enable --now <service>", "Start a service now and on every boot"),
      c("crontab -e", "Edit your scheduled jobs", { keywords: ["cron", "schedule"] }),
      c("crontab -l", "List your scheduled jobs"),
      c("sudo ufw allow 443", "Open a firewall port", { keywords: ["firewall"] }),
      c("sudo ufw status", "Firewall rules"),
      c("sudo tail -f /var/log/syslog", "Follow the system log"),
      c("sudo timedatectl set-timezone <zone>", "Set the server time zone"),
    ],
  },
  {
    id: "powershell",
    title: "Windows PowerShell",
    stack: "Shell & OS",
    platform: "Windows",
    keywords: ["windows", "powershell", "pwsh", "cmd"],
    entries: [
      c("Get-ChildItem -Recurse -Filter *.log", "Find files by name (like find)"),
      c('Select-String -Path *.ts -Pattern "<text>"', "Search inside files (like grep)"),
      c("Get-Content <file> -Tail 50 -Wait", "Follow a log file (like tail -f)"),
      c("Get-NetTCPConnection -LocalPort <port>", "Which process is using a port"),
      c("Get-Process <name>", "Find running processes"),
      c("Stop-Process -Name <name> -Force", "Kill processes by name", danger),
      c("Remove-Item -Recurse -Force node_modules", "Delete a folder (like rm -rf)", danger),
      c('$env:NODE_ENV = "production"', "Set an environment variable for this session"),
      c('[Environment]::SetEnvironmentVariable("<NAME>", "<value>", "User")', "Set a permanent user environment variable"),
      c("Set-ExecutionPolicy -Scope CurrentUser RemoteSigned", "Allow local scripts such as npm.ps1 to run"),
      c("Test-NetConnection <host> -Port <port>", "Is a port reachable"),
      c("Get-FileHash <file> -Algorithm SHA256", "Checksum of a file"),
      c("where.exe <command>", "Which binary will run for a command"),
      c("ipconfig /flushdns", "Flush the DNS cache"),
      c("winget install <id>", "Install an app from the command line"),
      c("wsl --install", "Install WSL with Ubuntu"),
      c("wsl -l -v", "WSL distributions and their versions"),
    ],
  },
  {
    id: "editors",
    title: "VS Code & editors",
    stack: "Shell & OS",
    keywords: ["editor", "vscode", "vs code", "vim", "ide"],
    entries: [
      c("code -r .", "Open a folder in the current VS Code window"),
      c("code -g <file>:<line>", "Open a file at a specific line"),
      c("code --diff <a> <b>", "Compare two files side by side"),
      c("code --install-extension <publisher.extension>", "Install an extension"),
      c("code --list-extensions > extensions.txt", "Save your extension list"),
      c("code --disable-extensions", "Start without extensions to rule them out"),
      c("cursor .", "Open a folder in Cursor"),
      c('export EDITOR="code --wait"', "Editor used by git, crontab and other tools"),
      c(":wq  :q!", "Vim: save and quit / quit without saving", { keywords: ["vim", "exit", "stuck"] }),
      c("nano <file>", "Simple terminal editor (Ctrl+O saves, Ctrl+X exits)"),
    ],
  },

  // ---- JavaScript
  {
    id: "node",
    title: "Node.js",
    stack: "JavaScript",
    keywords: ["node", "nodejs", "javascript", "js"],
    entries: [
      c("node --watch <file>.js", "Restart on file changes, no nodemon needed", { keywords: ["nodemon", "reload"] }),
      c("node --env-file=.env <file>.js", "Load a .env file without dotenv", { keywords: ["dotenv", "environment"] }),
      c("node --run <script>", "Run a package.json script faster than npm run (Node 22+)"),
      c("node <file>.ts", "Run TypeScript directly via type stripping (Node 22.18+ / 23.6+)", { keywords: ["typescript"] }),
      c("node --inspect <file>.js", "Debug in Chrome DevTools at chrome://inspect", { keywords: ["debugger"] }),
      c("node --inspect-brk <file>.js", "Same, but pause on the first line"),
      c("node --test", "Run tests with the built-in test runner"),
      c("node --max-old-space-size=4096 <file>.js", "Give Node 4 GB of heap", { keywords: ["heap out of memory", "memory"] }),
      c("node --cpu-prof <file>.js", "Write a CPU profile to open in DevTools", { keywords: ["performance", "profile"] }),
      c('node -e "console.log(1 + 1)"', "Run a one-line script"),
      c('node -p "process.versions"', "Print Node, V8 and OpenSSL versions"),
      c("node -p \"require('<pkg>/package.json').version\"", "Installed version of a package"),
      c("nvm install --lts", "Install the latest LTS Node", { keywords: ["version manager"] }),
      c("nvm use <version>", "Switch Node version for this shell"),
      c("nvm alias default <version>", "Make a version the default"),
      c("fnm use --install-if-missing", "Switch to the version in .nvmrc (fnm, faster than nvm)"),
      c("nvm ls", "Installed Node versions"),
      c("nvm use", "Use the version in .nvmrc"),
      c("node -v > .nvmrc", "Pin the current Node version for the project"),
      c("node --enable-source-maps <file>.js", "Stack traces that point at your TypeScript source"),
      c("node --trace-warnings <file>.js", "Show where a deprecation warning comes from"),
    ],
  },
  {
    id: "npm",
    title: "npm",
    stack: "JavaScript",
    keywords: ["npm", "package", "dependencies", "node_modules"],
    entries: [
      c("npm init -y", "Create a package.json with defaults"),
      c("npm ci", "Clean install exactly from the lockfile (use in CI)"),
      c("npm i <pkg>", "Install a dependency"),
      c("npm i -D <pkg>", "Install a dev dependency"),
      c("npm i <pkg>@latest", "Upgrade one package to its latest version"),
      c("npm uninstall <pkg>", "Remove a dependency"),
      c("npm run", "List every script in package.json"),
      c("npm run dev -- --port 4000", "Pass extra arguments through to a script"),
      c("npm outdated", "Packages with newer versions available"),
      c("npm update", "Update within the ranges in package.json"),
      c("npx npm-check-updates -u", "Bump every range in package.json to the latest", { keywords: ["ncu", "upgrade"] }),
      c("npm explain <pkg>", "Why a package is installed (alias: npm why)"),
      c("npm ls <pkg>", "Where a package sits in the dependency tree"),
      c("npm view <pkg> versions", "Every published version of a package"),
      c("npm audit", "Known vulnerabilities in your dependencies", { keywords: ["security"] }),
      c("npm audit fix", "Apply safe vulnerability fixes"),
      c("npm dedupe", "Remove duplicate packages from the tree"),
      c("npm cache clean --force", "Clear a corrupted npm cache"),
      c("npm link", "Use a local package in another project"),
      c("npm pack --dry-run", "Preview exactly which files would be published"),
      c("npm version patch", "Bump the version, commit and tag (minor and major too)"),
      c("npm publish --access public", "Publish a scoped package publicly"),
      c('npm pkg set scripts.lint="eslint ."', "Edit package.json from the command line"),
      c("npx depcheck", "Find unused dependencies"),
      c("npm i --legacy-peer-deps", "Install despite peer dependency conflicts (ERESOLVE)", { keywords: ["eresolve", "peer"] }),
      c("npm ls --depth=0", "Top-level installed packages"),
      c("npm ls -g --depth=0", "Globally installed packages"),
      c("npm run build --if-present", "Run a script only if it exists, handy in CI"),
      c("npm i -g npm@latest", "Upgrade npm itself"),
      c("npm whoami", "Which npm account you are logged in as"),
      c("npm config get registry", "Which registry npm installs from"),
      c("npm docs <pkg>", "Open a package's documentation"),
    ],
  },
  {
    id: "pnpm-yarn-bun",
    title: "pnpm, Yarn & Bun",
    stack: "JavaScript",
    keywords: ["package manager", "monorepo", "workspace"],
    entries: [
      c("corepack enable", "Use the pnpm or Yarn version pinned in package.json"),
      c("pnpm i", "Install dependencies (fast, disk-efficient)"),
      c("pnpm add <pkg>", "Add a dependency (-D for dev)"),
      c("pnpm up -i --latest", "Pick packages to upgrade interactively"),
      c("pnpm dlx <pkg>", "Run a package without installing it (like npx)"),
      c("pnpm -r run build", "Run a script in every workspace package"),
      c("pnpm --filter <pkg> dev", "Run a script in one workspace package"),
      c("pnpm why <pkg>", "Why a package is installed"),
      c("pnpm store prune", "Free disk space in the pnpm store"),
      c("yarn add <pkg>", "Add a dependency (-D for dev)"),
      c("yarn up <pkg>", "Upgrade a package (Yarn 2+)"),
      c("yarn dlx <pkg>", "Run a package without installing it"),
      c("yarn why <pkg>", "Why a package is installed"),
      c("bun install", "Install dependencies very quickly"),
      c("bun run dev", "Run a script with Bun"),
      c("bunx <pkg>", "Run a package without installing it"),
      c("bun test", "Run tests with Bun's built-in runner"),
      c("pnpm install --frozen-lockfile", "Install exactly the lockfile, fail if it's out of date (CI)"),
      c("pnpm outdated", "Packages with newer versions"),
      c("pnpm import", "Create pnpm-lock.yaml from an npm or Yarn lockfile"),
      c("yarn install --immutable", "Yarn's CI install"),
      c("bun update", "Update dependencies with Bun"),
    ],
  },
  {
    id: "ts-lint",
    title: "TypeScript, ESLint & Prettier",
    stack: "JavaScript",
    keywords: ["typescript", "ts", "lint", "format", "code quality"],
    entries: [
      c("npx tsc --noEmit", "Type-check without writing files", { keywords: ["type check"] }),
      c("npx tsc --noEmit --watch", "Type-check on every save"),
      c("npx tsc --init", "Create a tsconfig.json"),
      c("npx tsc --showConfig", "The final tsconfig after extends are applied"),
      c("npx tsx <file>.ts", "Run a TypeScript file directly"),
      c("npx tsx watch <file>.ts", "Run it and restart on changes"),
      c("npm init @eslint/config@latest", "Set up ESLint"),
      c("npx eslint .", "Lint the project"),
      c("npx eslint . --fix", "Lint and fix what can be fixed"),
      c("npx eslint --inspect-config", "Visual inspector for your flat config"),
      c("npx prettier --write .", "Format every file"),
      c("npx prettier --check .", "Fail if anything is unformatted (CI)"),
      c("npx @biomejs/biome check --write .", "Lint and format in one fast tool (Biome)"),
      c("npx knip", "Unused files, exports and dependencies"),
      c("npx madge --circular src", "Find circular imports"),
      c("npx husky init", "Set up git hooks"),
      c("npx lint-staged", "Lint only the files being committed"),
      c("npx eslint --cache .", "Lint only files changed since the last run"),
      c("npx tsc --generateTrace trace", "Profile slow type-checking"),
      c("npx publint", "Check a package's exports before you publish it"),
    ],
  },
  {
    id: "js-testing",
    title: "JS testing",
    stack: "JavaScript",
    keywords: ["test", "testing", "unit", "e2e"],
    entries: [
      c("npx vitest", "Run tests in watch mode"),
      c("npx vitest run --coverage", "Run once with a coverage report"),
      c('npx vitest -t "<name>"', "Only tests whose name matches"),
      c("npx vitest related <file>", "Only tests that import a given file"),
      c("npx vitest -u", "Update snapshots"),
      c("npx jest --watch", "Jest in watch mode"),
      c('npx jest -t "<name>"', "Only Jest tests whose name matches"),
      c("npx jest --coverage", "Jest coverage report"),
      c("npm init playwright@latest", "Set up Playwright"),
      c("npx playwright install --with-deps", "Download browsers and system dependencies"),
      c("npx playwright test", "Run end-to-end tests"),
      c("npx playwright test --ui", "Visual runner with time-travel debugging"),
      c("npx playwright test --headed --project=chromium", "Watch the browser while one project runs"),
      c("npx playwright codegen <url>", "Record clicks into a test"),
      c("npx playwright show-report", "Open the last HTML report"),
      c("npx cypress open", "Interactive Cypress runner"),
      c("npx vitest --ui", "Browser UI for your Vitest tests"),
      c("npx jest -u", "Update Jest snapshots"),
      c("npx jest --runInBand", "Run Jest tests one at a time, easier to debug"),
      c("npx playwright test --debug", "Step through a test with the inspector"),
      c("npx playwright test --last-failed", "Rerun only the tests that failed"),
      c("npx cypress run", "Run Cypress headless in CI"),
    ],
  },

  // ---- Frameworks
  {
    id: "nextjs",
    title: "Next.js",
    stack: "Frameworks",
    keywords: ["next", "nextjs", "react", "vercel", "turbopack"],
    entries: [
      c("npx create-next-app@latest <name>", "Create a new Next.js app"),
      c("next dev", "Dev server; Turbopack is the default from v16"),
      c("next dev -p 4000", "Dev server on another port"),
      c("next dev -H 0.0.0.0", "Reachable from your phone on the same network"),
      c("next dev --experimental-https", "Local HTTPS with a self-signed certificate"),
      c("next build", "Production build"),
      c("next build --webpack", "Build with webpack instead of Turbopack"),
      c("next build --debug", "Build output that also lists rewrites, redirects and headers"),
      c("next build --debug-prerender", "Readable errors when prerendering fails"),
      c("next start", "Serve the production build"),
      c("next typegen", "Generate route types without a full build (run before tsc in CI)"),
      c("next info", "System and version details for bug reports"),
      c("next upgrade", "Upgrade Next.js to the latest release"),
      c("npx @next/codemod upgrade major", "Upgrade and run the matching codemods"),
      c("next experimental-analyze", "Inspect bundle sizes"),
      c("next telemetry --disable", "Turn off anonymous telemetry"),
      c("npx eslint .", "Lint a Next.js app; next lint was removed in v16"),
      c("rm -rf .next", "Clear the build cache when things look stale"),
      c("next start -p 4000", "Serve the production build on another port"),
      c("next build --profile", "Production build with React profiling enabled"),
      c('next build --debug-build-paths="<pattern>"', "Build only matching routes while debugging"),
    ],
  },
  {
    id: "react-vite",
    title: "React & Vite",
    stack: "Frameworks",
    keywords: ["react", "vite", "frontend", "spa"],
    entries: [
      c("npm create vite@latest", "New React, Vue or Svelte app on Vite"),
      c("npx vite", "Vite dev server"),
      c("npx vite --host", "Dev server reachable on your network"),
      c("npx vite build", "Production build"),
      c("npx vite preview", "Serve the production build locally"),
      c("npx shadcn@latest init", "Set up shadcn/ui"),
      c("npx shadcn@latest add <component>", "Add a shadcn/ui component"),
      c("npx storybook@latest init", "Set up Storybook"),
      c("npx serve dist", "Serve a static build folder"),
      c("npx source-map-explorer dist/**/*.js", "See what makes the bundle big"),
      c("rm -rf node_modules/.vite", "Clear Vite's dependency cache"),
      c("npx vite --force", "Re-bundle dependencies, ignoring the cache"),
      c("npx vite build --mode staging", "Build with .env.staging"),
    ],
  },
  {
    id: "svelte",
    title: "Svelte & SvelteKit",
    stack: "Frameworks",
    keywords: ["svelte", "sveltekit", "sv", "vite"],
    entries: [
      c("npx sv create <name>", "New SvelteKit or Svelte project"),
      c("npm run dev -- --open", "Dev server and open the browser"),
      c("npm run dev -- --host", "Dev server reachable on your network"),
      c("npm run build", "Production build"),
      c("npm run preview", "Serve the production build locally"),
      c("npx sv add", "Pick integrations to add"),
      c("npx sv add tailwindcss", "Add Tailwind CSS"),
      c("npx sv add eslint prettier", "Add linting and formatting"),
      c("npx sv add vitest playwright", "Add unit and end-to-end tests"),
      c("npx sv add drizzle", "Add Drizzle ORM", { keywords: ["database"] }),
      c("npx sv add paraglide", "Add translations", { keywords: ["i18n"] }),
      c("npx sv add sveltekit-adapter", "Pick a deploy adapter (node, static, Vercel, Cloudflare, Netlify)"),
      c("npx sv check", "Type-check .svelte files"),
      c("npx svelte-check --watch", "Re-check on every save"),
      c("npx sv migrate svelte-5", "Migrate Svelte 4 components to runes"),
      c("npx svelte-kit sync", "Regenerate ./$types; fixes \"Cannot find module './$types'\""),
      c("node build", "Run an app built with adapter-node"),
      c("ORIGIN=https://<domain> PORT=3000 node build", "Production run with the right origin; fixes cross-site POST errors"),
      c("rm -rf .svelte-kit node_modules/.vite", "Clear SvelteKit and Vite caches"),
      c("npx sv add mdsvex", "Write pages in Markdown"),
      c("npx sv migrate", "List the available migrations"),
    ],
  },

  // ---- Python
  {
    id: "python",
    title: "Python",
    stack: "Python",
    keywords: ["python", "py"],
    entries: [
      c("python3 --version", "Python version"),
      c("python -m <module>", "Run a module with this exact interpreter (safer than a bare tool name)"),
      c("python -i <file>.py", "Run a script, then stay in the REPL with its variables"),
      c('python -c "print(1 + 1)"', "Run a one-line script"),
      c("python -m http.server 8000", "Serve the current folder over HTTP", { keywords: ["static", "server"] }),
      c("python -m json.tool <file>.json", "Pretty-print JSON"),
      c("python -m pdb <file>.py", "Run under the debugger", { keywords: ["breakpoint", "debug"] }),
      c("python -m cProfile -s time <file>.py", "Which functions are slow", { keywords: ["profile", "performance"] }),
      c("python -X importtime <file>.py", "Which imports slow down startup"),
      c("ipython", "Friendlier interactive shell"),
      c("jupyter lab", "Open JupyterLab", { keywords: ["notebook"] }),
      c("python -m ipykernel install --user --name <env>", "Make a virtualenv available as a notebook kernel", { keywords: ["jupyter"] }),
      c("jupyter nbconvert --to script <file>.ipynb", "Convert a notebook to a .py file"),
      c("pyinstaller --onefile <file>.py", "Bundle a script into one executable"),
      c("python -m pip install --upgrade pip", "Upgrade pip itself"),
      c("python -m unittest", "Run tests with the standard library runner"),
      c("python -m uuid", "Generate a UUID (Python 3.12+)"),
    ],
  },
  {
    id: "python-env",
    title: "Python: env & packages",
    stack: "Python",
    keywords: ["python", "pip", "venv", "virtualenv", "uv", "poetry", "dependencies"],
    entries: [
      c("python -m venv .venv", "Create a virtual environment"),
      c("source .venv/bin/activate", "Activate it on macOS or Linux"),
      c(".venv\\Scripts\\activate", "Activate the virtual environment", windows),
      c("deactivate", "Leave the virtual environment"),
      c("python -m pip install <pkg>", "Install into the active interpreter, never the wrong one"),
      c("pip install -r requirements.txt", "Install from a requirements file"),
      c("pip install -e .", "Install your own project in editable mode"),
      c("pip freeze > requirements.txt", "Pin current versions to a file"),
      c("pip list --outdated", "Packages with updates"),
      c("pip show <pkg>", "Version, location and dependencies of a package"),
      c("uv init <name>", "New project with pyproject.toml (uv, very fast)"),
      c("uv add <pkg>", "Add a dependency and update uv.lock"),
      c("uv add --dev pytest", "Add a dev dependency"),
      c("uv sync", "Install exactly what the lockfile says"),
      c("uv run <file>.py", "Run inside the project environment, no activate needed"),
      c("uv pip install -r requirements.txt", "Drop-in pip replacement, many times faster"),
      c("uv python install 3.13", "Install a Python version"),
      c("uvx <tool>", "Run a tool without installing it (like npx)"),
      c("uv tool install <tool>", "Install a CLI tool globally, isolated"),
      c("uv lock --upgrade", "Upgrade every locked version"),
      c("poetry add <pkg>", "Add a dependency with Poetry"),
      c("poetry install", "Install from poetry.lock"),
      c("poetry run python <file>.py", "Run inside the Poetry environment"),
      c("pyenv install 3.13", "Install a Python version with pyenv"),
      c("pyenv local 3.13", "Pin the Python version for this folder"),
      c("pipx install <tool>", "Install a Python CLI globally, isolated"),
      c('pip install "<pkg>==1.2.3"', "Install an exact version"),
      c("pip uninstall <pkg>", "Remove a package"),
      c("pip cache purge", "Clear pip's download cache"),
    ],
  },
  {
    id: "python-quality",
    title: "Python: lint & test",
    stack: "Python",
    keywords: ["python", "lint", "format", "test", "pytest"],
    entries: [
      c("ruff check .", "Lint very quickly"),
      c("ruff check . --fix", "Lint and fix"),
      c("ruff format .", "Format (Black-compatible)"),
      c("black .", "Format with Black"),
      c("mypy .", "Type-check your Python code"),
      c("pyright", "Faster type checker, the engine behind Pylance"),
      c("pre-commit install", "Run hooks before every commit"),
      c("pre-commit run --all-files", "Run every hook on the whole repo"),
      c("pytest", "Run all tests it can find"),
      c("pytest -v", "One line per test"),
      c('pytest -k "<name>"', "Only tests whose name matches"),
      c("pytest <file>.py::<test_name>", "One specific test"),
      c("pytest -x", "Stop at the first failure"),
      c("pytest --lf", "Rerun only the tests that failed last time"),
      c("pytest -s", "Show print() output"),
      c("pytest --pdb", "Open the debugger at the failure"),
      c("pytest -n auto", "Run in parallel (pytest-xdist)"),
      c("pytest --cov=<package> --cov-report=html", "Coverage report (pytest-cov)"),
    ],
  },
  {
    id: "django",
    title: "Django",
    stack: "Python",
    keywords: ["django", "python", "manage.py", "migrations"],
    entries: [
      c("django-admin startproject <name> .", "New project in the current folder"),
      c("python manage.py startapp <app>", "New app folder with models, views and admin"),
      c("python manage.py runserver", "Dev server on port 8000"),
      c("python manage.py makemigrations", "Create migrations from model changes"),
      c("python manage.py migrate", "Apply migrations"),
      c("python manage.py showmigrations", "Which migrations are applied"),
      c("python manage.py sqlmigrate <app> <number>", "SQL a migration will run"),
      c("python manage.py createsuperuser", "Create an admin user"),
      c("python manage.py shell", "Python shell with Django loaded"),
      c("python manage.py dbshell", "Database shell"),
      c("python manage.py collectstatic", "Collect static files for production"),
      c("python manage.py test", "Run Django tests with a throwaway test database"),
      c("python manage.py check --deploy", "Security checklist for production settings"),
      c("python manage.py runserver 0.0.0.0:8000", "Dev server reachable on your network"),
      c("python manage.py makemigrations --check --dry-run", "Fail CI when a migration is missing"),
      c("python manage.py migrate <app> <number>", "Migrate forwards or back to a specific migration"),
      c("python manage.py changepassword <user>", "Reset a user's password"),
      c("python manage.py flush", "Delete all data but keep the tables", danger),
    ],
  },
  {
    id: "fastapi-flask",
    title: "FastAPI, Flask & Alembic",
    stack: "Python",
    keywords: ["fastapi", "flask", "uvicorn", "gunicorn", "alembic", "sqlalchemy", "api"],
    entries: [
      c("fastapi dev main.py", "FastAPI dev server with reload; docs at /docs"),
      c("fastapi run main.py", "FastAPI in production mode"),
      c("uvicorn main:app --reload", "Any ASGI app with auto-reload"),
      c("uvicorn main:app --host 0.0.0.0 --port 8000 --workers 4", "Production-style Uvicorn"),
      c("flask --app app run --debug", "Flask with debugger and reload"),
      c("flask --app app routes", "List every Flask route"),
      c("gunicorn app:app -w 4 -b 0.0.0.0:8000", "Production server for Flask or Django (WSGI)"),
      c("gunicorn main:app -k uvicorn.workers.UvicornWorker -w 4", "Gunicorn managing Uvicorn workers for FastAPI"),
      c("alembic init migrations", "Set up Alembic"),
      c('alembic revision --autogenerate -m "<message>"', "Create a migration from model changes"),
      c("alembic upgrade head", "Apply all migrations"),
      c("alembic downgrade -1", "Roll back one migration", danger),
      c("alembic history", "List migrations"),
    ],
  },

  // ---- More languages
  {
    id: "go",
    title: "Go",
    stack: "More languages",
    keywords: ["go", "golang"],
    entries: [
      c("go mod init <module>", "Start a new module"),
      c("go run .", "Build and run the package in this folder"),
      c("go build -o bin/app .", "Build a binary into bin/app"),
      c("GOOS=linux GOARCH=amd64 go build -o bin/app .", "Cross-compile for Linux servers"),
      c("go test ./...", "Run tests in every package"),
      c("go test -run <TestName> -v ./...", "Run matching tests with output"),
      c("go test -race ./...", "Run tests with the race detector"),
      c("go test -cover ./...", "Test coverage per package"),
      c("go mod tidy", "Add missing and remove unused modules"),
      c("go get <pkg>@latest", "Add or upgrade a dependency"),
      c("go install <pkg>@latest", "Install a Go CLI tool"),
      c("go fmt ./...", "Format all code with gofmt"),
      c("go vet ./...", "Report likely mistakes"),
      c("go doc <pkg>", "Docs for a package or symbol"),
    ],
  },
  {
    id: "rust",
    title: "Rust & Cargo",
    stack: "More languages",
    keywords: ["rust", "cargo", "rustup"],
    entries: [
      c("rustup update", "Update the Rust toolchain"),
      c("cargo new <name>", "New binary project with Cargo.toml and src/main.rs"),
      c("cargo run", "Build and run the project (debug build)"),
      c("cargo check", "Type-check quickly without producing a binary"),
      c("cargo build --release", "Optimised build in target/release"),
      c("cargo test", "Run unit, integration and doc tests"),
      c("cargo test <name> -- --nocapture", "Run matching tests and show println! output"),
      c("cargo add <crate>", "Add a dependency"),
      c("cargo fmt", "Format code with rustfmt"),
      c("cargo clippy", "Lint with Clippy for common mistakes and style"),
      c("cargo clippy --fix", "Apply lint fixes"),
      c("cargo update", "Update Cargo.lock within your version ranges"),
      c("cargo tree", "Dependency tree; find why a crate is included"),
      c("cargo install <crate>", "Install a Rust CLI tool"),
      c("cargo clean", "Delete the target folder"),
      c("cargo doc --open", "Build and open docs for your crate and its dependencies"),
    ],
  },
  {
    id: "java",
    title: "Java, Maven & Gradle",
    stack: "More languages",
    keywords: ["java", "jvm", "maven", "gradle", "spring", "kotlin"],
    entries: [
      c("java -version", "Installed Java version"),
      c("jshell", "Interactive Java shell"),
      c("sdk install java", "Install the default JDK with SDKMAN! (sdk list java shows other versions)"),
      c("export JAVA_HOME=$(/usr/libexec/java_home -v 17)", "Switch the active JDK", mac),
      c("mvn clean install", "Build, test and install to the local repository"),
      c("mvn test -Dtest=<Class>", "Run one test class"),
      c("mvn dependency:tree", "Maven dependency tree; find version conflicts"),
      c("./mvnw spring-boot:run", "Run a Spring Boot app with the Maven wrapper"),
      c("./gradlew build", "Build with the Gradle wrapper"),
      c("./gradlew test", "Run tests with the Gradle wrapper"),
      c("./gradlew bootRun", "Run a Spring Boot app with Gradle"),
      c("./gradlew dependencies", "Gradle dependency tree per configuration"),
      c("./gradlew build --refresh-dependencies", "Ignore cached dependencies and fetch again"),
    ],
  },
  {
    id: "dotnet",
    title: ".NET",
    stack: "More languages",
    keywords: ["dotnet", ".net", "c#", "csharp", "asp.net"],
    entries: [
      c("dotnet new list", "Available project templates"),
      c("dotnet new webapi -n <name>", "New Web API project"),
      c("dotnet run", "Build and run the project in this folder"),
      c("dotnet watch", "Run with hot reload"),
      c("dotnet build", "Compile the project or solution"),
      c("dotnet test", "Run tests in the solution"),
      c("dotnet add package <package>", "Add a NuGet package"),
      c("dotnet restore", "Restore dependencies"),
      c("dotnet format", "Format code to your .editorconfig rules"),
      c('dotnet ef migrations add <name>', "Create an Entity Framework migration"),
      c("dotnet ef database update", "Apply migrations"),
      c("dotnet publish -c Release", "Production build ready to deploy"),
    ],
  },
  {
    id: "php",
    title: "PHP, Composer & Laravel",
    stack: "More languages",
    keywords: ["php", "composer", "laravel", "artisan"],
    entries: [
      c("php -S localhost:8000", "Built-in development server"),
      c("composer install", "Install from composer.lock"),
      c("composer require <vendor/package>", "Add a dependency"),
      c("composer update", "Update dependencies"),
      c("composer dump-autoload", "Rebuild the autoloader after adding classes"),
      c("php artisan serve", "Laravel dev server"),
      c("php artisan migrate", "Apply migrations"),
      c("php artisan migrate:fresh --seed", "Drop every table, migrate and seed", danger),
      c("php artisan make:model <Name> -m", "Model with a migration"),
      c("php artisan tinker", "Interactive shell with the app loaded"),
      c("php artisan route:list", "Every route with its method, URI and controller"),
      c("php artisan optimize:clear", "Clear config, route, view and cache"),
    ],
  },

  // ---- Mobile
  {
    id: "react-native",
    title: "React Native & Expo",
    stack: "Mobile",
    keywords: ["react native", "rn", "expo", "metro", "mobile"],
    entries: [
      c("npx @react-native-community/cli init <name>", "New bare React Native project"),
      c("npx create-expo-app@latest <name>", "New Expo project"),
      c("npx react-native start --reset-cache", "Metro with a cleared cache"),
      c("npx react-native run-android", "Build and launch on Android"),
      c('npx react-native run-ios --simulator="iPhone 16"', "Build and launch on a specific simulator"),
      c("npx react-native doctor", "Check your environment and fix problems"),
      c("npx react-native info", "Environment details for bug reports"),
      c("npx expo start -c", "Expo dev server with a cleared cache"),
      c("npx expo install --check", "Fix dependency versions that don't match your SDK"),
      c("npx expo install <pkg>", "Install the version compatible with your SDK"),
      c("npx expo prebuild --clean", "Regenerate the android and ios folders"),
      c("npx expo-doctor", "Diagnose common Expo project issues"),
      c("eas build -p android --profile preview", "Cloud build an installable APK"),
      c("eas build -p ios", "Cloud build for iOS"),
      c("eas submit -p ios", "Upload a build to App Store Connect"),
      c("eas update --branch production", "Ship an over-the-air JS update"),
      c("watchman watch-del-all", "Reset Watchman when Metro misses file changes"),
      c("npx expo run:android", "Build a development build locally"),
      c("npx expo run:ios", "Build a development build locally for iOS"),
      c("npx expo export", "Export the JavaScript bundle and assets"),
      c("eas build --local", "Run an EAS build on your own machine"),
      c("npx react-native log-android", "Stream JS logs from Android"),
      c("npx react-native log-ios", "Stream JS logs from iOS"),
    ],
  },
  {
    id: "android",
    title: "Android, adb & Gradle",
    stack: "Mobile",
    keywords: ["android", "adb", "gradle", "apk", "aab", "emulator"],
    entries: [
      c("adb devices", "Connected devices and emulators"),
      c("adb reverse tcp:8081 tcp:8081", "Let a USB device reach Metro on your machine"),
      c("adb logcat *:E", "Only error logs"),
      c("adb logcat | grep ReactNativeJS", "Only JavaScript logs from a React Native app"),
      c("adb shell input keyevent 82", "Open the React Native dev menu"),
      c("adb install -r <file>.apk", "Install or reinstall an APK"),
      c("adb uninstall <package>", "Uninstall an app"),
      c('adb shell am start -W -a android.intent.action.VIEW -d "<url>"', "Test a deep link", { keywords: ["deep link", "intent"] }),
      c("adb shell pm clear <package>", "Wipe an app's data", danger),
      c("adb exec-out screencap -p > screen.png", "Screenshot the device"),
      c("emulator -list-avds", "List emulators; emulator -avd <name> starts one"),
      c("cd android && ./gradlew clean", "Clear the Android build"),
      c("cd android && ./gradlew assembleRelease", "Build a release APK"),
      c("cd android && ./gradlew bundleRelease", "Build an AAB for the Play Store"),
      c("cd android && ./gradlew signingReport", "SHA-1 and SHA-256 for Firebase, Google Sign-In and Maps", { keywords: ["sha1", "fingerprint"] }),
      c("keytool -genkeypair -v -keystore release.keystore -alias <alias> -keyalg RSA -keysize 2048 -validity 10000", "Create a release signing key"),
      c("keytool -list -v -keystore <file>.keystore", "Fingerprints of an existing keystore"),
      c("adb kill-server && adb start-server", "Fixes unauthorized or missing devices"),
      c("adb tcpip 5555 && adb connect <ip>:5555", "Use adb over Wi-Fi", { keywords: ["wireless"] }),
      c("adb shell screenrecord /sdcard/demo.mp4", "Record the device screen"),
      c("adb pull <remote> <local>", "Copy a file from the device"),
      c("adb shell dumpsys package <package> | grep versionName", "Installed version of an app"),
      c("cd android && ./gradlew app:dependencies", "Dependency tree; find duplicate class conflicts"),
      c("cd android && ./gradlew --stop", "Stop Gradle daemons that are stuck or eating memory"),
    ],
  },
  {
    id: "ios",
    title: "iOS, Xcode & CocoaPods",
    stack: "Mobile",
    platform: "macOS",
    keywords: ["ios", "xcode", "simulator", "pods", "cocoapods", "iphone"],
    entries: [
      c("cd ios && pod install", "Install native iOS dependencies"),
      c("cd ios && pod install --repo-update", "Same, with fresh pod specs"),
      c("cd ios && rm -rf Pods Podfile.lock && pod install", "Reinstall pods from scratch"),
      c("xcrun simctl list devices", "Available simulators"),
      c('xcrun simctl openurl booted "<url>"', "Test a deep link on the running simulator", { keywords: ["deep link"] }),
      c("xcrun simctl io booted screenshot screen.png", "Screenshot the simulator"),
      c("xcrun simctl erase all", "Reset every simulator", danger),
      c("rm -rf ~/Library/Developer/Xcode/DerivedData", "Clear Xcode's build cache", { keywords: ["clean"] }),
      c("xcodebuild -showsdks", "Installed SDKs"),
      c("sudo xcode-select -s /Applications/Xcode.app", "Point the command-line tools at a specific Xcode"),
      c('xcrun simctl boot "<device>"', "Boot a simulator"),
      c("open -a Simulator", "Open the Simulator app"),
      c("xcrun simctl io booted recordVideo demo.mov", "Record the simulator screen"),
      c("xcrun simctl push booted <bundle-id> payload.apns", "Send a test push notification", { keywords: ["notification", "apns"] }),
      c("xcrun xctrace list devices", "Connected devices and simulators"),
      c("pod deintegrate", "Remove CocoaPods from the Xcode project"),
      c("sudo xcodebuild -license accept", "Accept the Xcode license from the terminal"),
    ],
  },

  // ---- Infra & Data
  {
    id: "docker",
    title: "Docker",
    stack: "Infra & Data",
    keywords: ["docker", "container", "image", "compose"],
    entries: [
      c("docker ps -a", "All containers, including stopped ones"),
      c("docker images", "Local images"),
      c("docker build -t <name> .", "Build an image from the Dockerfile here"),
      c("docker run --rm -p 3000:3000 <image>", "Run an image, map a port, remove it on exit"),
      c("docker run --rm -it <image> sh", "Poke around inside an image"),
      c("docker exec -it <container> sh", "Shell into a running container"),
      c("docker logs -f <container>", "Follow a container's logs"),
      c("docker stats", "Live CPU and memory per container"),
      c("docker compose up -d", "Start services in the background"),
      c("docker compose up -d --build", "Rebuild images, then start"),
      c("docker compose logs -f <service>", "Follow one service's logs"),
      c("docker compose down", "Stop and remove the services"),
      c("docker compose down -v", "Same, and delete their volumes (data)", danger),
      c("docker system df", "Disk used by images, containers and volumes"),
      c("docker system prune -a", "Delete everything unused to free space", danger),
      c("docker compose ps", "Status of each service"),
      c("docker compose exec <service> sh", "Shell into a running service"),
      c("docker compose restart <service>", "Restart one service"),
      c("docker compose config", "The fully resolved compose file, env vars included"),
      c("docker cp <container>:<path> .", "Copy a file out of a container"),
      c("docker inspect <container>", "Full config, IP address and mounts of a container"),
      c("docker volume ls", "List volumes"),
      c("docker build --no-cache -t <name> .", "Rebuild every layer from scratch"),
      c("docker buildx build --platform linux/amd64 -t <name> .", "Build for x86 servers from an Apple Silicon Mac", { keywords: ["arm", "m1", "m2"] }),
      c("docker tag <image> <repo>:<tag>", "Tag an image for a registry"),
      c("docker push <repo>:<tag>", "Push an image to a registry"),
      c("docker stop $(docker ps -q)", "Stop every running container", danger),
    ],
  },
  {
    id: "kubernetes",
    title: "Kubernetes",
    stack: "Infra & Data",
    keywords: ["kubernetes", "k8s", "kubectl", "cluster", "pod"],
    entries: [
      c("kubectl config get-contexts", "Clusters you can talk to"),
      c("kubectl config use-context <context>", "Switch to another cluster"),
      c("kubectl get pods -A", "Pods in every namespace"),
      c("kubectl get all -n <namespace>", "Everything in a namespace"),
      c("kubectl describe pod <pod>", "Pod details and events; start here when debugging"),
      c("kubectl logs -f <pod>", "Follow a pod's logs"),
      c("kubectl logs <pod> --previous", "Logs from the crashed container before the restart", { keywords: ["crashloopbackoff"] }),
      c("kubectl exec -it <pod> -- sh", "Shell into a pod"),
      c("kubectl port-forward svc/<service> 8080:80", "Reach a service on localhost:8080"),
      c("kubectl apply -f <file>.yaml", "Create or update resources from a file"),
      c("kubectl rollout restart deploy/<deployment>", "Restart a deployment's pods"),
      c("kubectl rollout undo deploy/<deployment>", "Roll back to the previous revision"),
      c("kubectl scale deploy/<deployment> --replicas=3", "Change replica count"),
      c("kubectl top pods", "CPU and memory per pod (needs metrics-server)"),
      c("kubectl get events --sort-by=.lastTimestamp", "Recent cluster events, newest last"),
      c("kubectl get pods -w", "Watch pods change state live"),
      c("kubectl get pod <pod> -o yaml", "Full definition of a pod"),
      c("kubectl delete pod <pod>", "Delete a pod so its deployment recreates it"),
      c("kubectl config set-context --current --namespace=<namespace>", "Set the default namespace"),
      c("kubectl create secret generic <name> --from-literal=<KEY>=<value>", "Create a secret"),
      c("kubectl get secret <name> -o jsonpath='{.data.<KEY>}' | base64 -d", "Read a secret's value"),
      c("kubectl rollout status deploy/<deployment>", "Wait for a rollout to finish"),
      c("kubectl diff -f <file>.yaml", "Preview what apply would change"),
      c("kubectl explain deployment.spec", "Docs for any resource field"),
      c("helm upgrade --install <release> <chart> -f values.yaml", "Install or upgrade a Helm release"),
      c("helm list -A", "Helm releases in every namespace"),
      c("helm rollback <release> <revision>", "Roll a release back"),
    ],
  },
  {
    id: "databases",
    title: "Databases",
    stack: "Infra & Data",
    keywords: ["database", "db", "sql", "postgres", "mysql", "mongodb", "redis"],
    entries: [
      c("psql -h <host> -U <user> -d <db>", "Connect to Postgres"),
      c("\\dt  \\d <table>  \\l  \\q", "psql: list tables, describe a table, list databases, quit"),
      c("pg_dump <db> > backup.sql", "Back up a Postgres database"),
      c("psql <db> < backup.sql", "Restore a Postgres backup"),
      c("createdb <db>", "Create a Postgres database"),
      c("dropdb <db>", "Delete a Postgres database", danger),
      c("mysql -u root -p", "Connect to MySQL"),
      c("mysqldump -u <user> -p <db> > backup.sql", "Back up a MySQL database"),
      c('mongosh "mongodb://localhost:27017"', "Connect to MongoDB"),
      c("mongodump --uri <uri>", "Back up MongoDB"),
      c("mongorestore --uri <uri> dump/", "Restore a MongoDB dump"),
      c("sqlite3 <file>.db", "Open a SQLite database (.tables, .schema, .quit)"),
      c("redis-cli", "Interactive Redis shell on localhost:6379"),
      c("redis-cli --scan --pattern 'user:*'", "Find keys without blocking the server (unlike KEYS)"),
      c("redis-cli FLUSHALL", "Delete every key in every Redis database", danger),
      c("npx prisma migrate dev", "Create and apply a Prisma migration"),
      c("npx prisma studio", "Browse data in a web UI"),
      c("npx drizzle-kit generate", "Generate Drizzle migrations; drizzle-kit migrate applies them"),
      c("\\x", "psql: expanded output for wide rows"),
      c("pg_isready -h <host>", "Is Postgres accepting connections"),
      c("pg_dump -Fc <db> > <file>.dump", "Compressed custom-format Postgres backup"),
      c("pg_restore -d <db> <file>.dump", "Restore a custom-format backup"),
      c("redis-cli MONITOR", "Watch every command live (debugging only, it's heavy)"),
      c("redis-cli TTL <key>", "Seconds left before a key expires"),
      c("npx prisma generate", "Regenerate the Prisma client after a schema change"),
      c("npx prisma migrate deploy", "Apply pending migrations in production"),
      c("npx prisma db push", "Sync the schema without a migration while prototyping"),
      c("npx prisma migrate reset", "Drop the database and reapply every migration", danger),
      c("npx drizzle-kit studio", "Browse data with Drizzle Studio"),
    ],
  },
  {
    id: "deploy",
    title: "Deploy & hosting",
    stack: "Infra & Data",
    keywords: ["deploy", "hosting", "production", "server"],
    entries: [
      c("vercel", "Deploy a preview to Vercel"),
      c("vercel --prod", "Deploy to production"),
      c("vercel env pull", "Download env variables to .env.local"),
      c("vercel logs <url>", "Logs for a deployment"),
      c("netlify deploy --prod", "Deploy to Netlify"),
      c("npx wrangler deploy", "Deploy to Cloudflare Workers"),
      c("npx wrangler dev", "Run a Worker locally"),
      c("firebase deploy", "Deploy to Firebase"),
      c("fly deploy", "Deploy to Fly.io"),
      c("pm2 start <file>.js --name <name>", "Keep a Node app running on a server"),
      c("pm2 logs", "Logs of pm2-managed apps"),
      c("pm2 startup && pm2 save", "Restart pm2 apps after a reboot"),
      c("sudo nginx -t && sudo systemctl reload nginx", "Check the nginx config, then reload without downtime"),
      c("sudo certbot --nginx -d <domain>", "Free HTTPS certificate from Let's Encrypt"),
      c("ngrok http 3000", "Public URL for localhost:3000", { keywords: ["tunnel", "webhook"] }),
      c("cloudflared tunnel --url http://localhost:3000", "Free public tunnel with Cloudflare"),
      c("vercel link", "Link the folder to a Vercel project"),
      c("vercel rollback", "Roll production back to the previous deployment"),
      c("pm2 restart <name>", "Restart an app managed by pm2"),
      c("pm2 monit", "Live CPU, memory and logs for pm2 apps"),
      c("heroku logs --tail", "Follow Heroku logs"),
    ],
  },
  {
    id: "security",
    title: "Security & auditing",
    stack: "Infra & Data",
    keywords: ["security", "secret", "audit", "vulnerability"],
    entries: [
      c("openssl rand -hex 32", "Random 256-bit secret", { keywords: ["key", "token"] }),
      c("openssl rand -base64 32", "Random secret in Base64"),
      c("npx gitleaks detect", "Find secrets committed to the repo"),
      c("npm audit --omit=dev", "Vulnerabilities in production dependencies only"),
      c("pip-audit", "Vulnerabilities in Python dependencies"),
      c("docker scout cves <image>", "Vulnerabilities in a Docker image"),
      c("npx lighthouse <url> --view", "Performance, accessibility and SEO audit"),
      c("shasum -a 256 <file>", "SHA-256 checksum of a file", { keywords: ["hash", "verify"] }),
      c("gpg --verify <file>.sig <file>", "Verify a signed download"),
      c("ssh-keygen -lf ~/.ssh/id_ed25519.pub", "Fingerprint of an SSH key"),
      c("openssl x509 -in <cert>.pem -text -noout", "Read a certificate's subject, issuer and expiry"),
      c("mkcert localhost", "Locally trusted HTTPS certificate for development"),
      c("trivy image <image>", "Scan an image for vulnerabilities and secrets"),
    ],
  },
  {
    id: "cloud",
    title: "AWS, cloud CLIs & Terraform",
    stack: "Infra & Data",
    keywords: ["aws", "cloud", "terraform", "iac", "gcloud", "azure", "s3"],
    entries: [
      c("aws configure", "Set up access keys and a default region"),
      c("aws sso login --profile <profile>", "Sign in with AWS SSO"),
      c("export AWS_PROFILE=<profile>", "Use a profile for this shell"),
      c("aws sts get-caller-identity", "Which account and role you are actually using"),
      c("aws s3 ls s3://<bucket>", "List a bucket"),
      c("aws s3 cp <file> s3://<bucket>/", "Upload a file"),
      c("aws s3 sync ./dist s3://<bucket> --delete", "Mirror a folder to a bucket, deleting extra files", danger),
      c("aws logs tail <log-group> --follow", "Follow CloudWatch logs"),
      c("aws ecr get-login-password | docker login --username AWS --password-stdin <registry>", "Log Docker in to ECR"),
      c("gcloud auth login", "Sign in to Google Cloud"),
      c("gcloud config set project <project>", "Switch Google Cloud project"),
      c("az login", "Sign in to Azure"),
      c("terraform init", "Download providers and set up the backend"),
      c("terraform fmt -recursive", "Format every .tf file"),
      c("terraform validate", "Check the configuration"),
      c("terraform plan -out=tfplan", "Preview changes and save the plan"),
      c("terraform apply tfplan", "Apply exactly the saved plan"),
      c("terraform state list", "Resources Terraform is tracking"),
      c("terraform output", "Show output values"),
      c("terraform destroy", "Delete everything this configuration created", danger),
    ],
  },

  // ---- Troubleshooting
  {
    id: "fixes",
    title: "Common fixes",
    stack: "Troubleshooting",
    keywords: ["fix", "error", "broken", "not working", "troubleshoot"],
    entries: [
      c("rm -rf node_modules package-lock.json && npm i", "Fixes most dependency install problems: a clean reinstall", { keywords: ["reinstall"] }),
      c("npm i --legacy-peer-deps", "Fixes ERESOLVE unable to resolve dependency tree"),
      c("sudo chown -R $(whoami) ~/.npm", "Fixes EACCES permission errors from npm"),
      c("export NODE_OPTIONS=--max-old-space-size=4096", "Fixes JavaScript heap out of memory during builds"),
      c("ulimit -n 65536", "Fixes EMFILE: too many open files (Metro, Jest, watchers)"),
      c("lsof -ti :<port> | xargs kill -9", "Fixes EADDRINUSE: address already in use", danger),
      c("git rm -r --cached . && git add .", "Fixes .gitignore not ignoring files that were already committed"),
      c("git pull --rebase", "Fixes push rejected because the remote contains work you don't have"),
      c("git config --global --add safe.directory <path>", "Fixes detected dubious ownership in repository"),
      c("git remote set-url origin git@github.com:<owner/repo>.git", "Fixes password authentication was removed, by switching to SSH"),
      c("git config --global http.postBuffer 524288000", "Fixes RPC failed; HTTP 400 on large pushes over HTTPS"),
      c("git config --global core.autocrlf input", "Fixes whole-file diffs caused by Windows line endings"),
      c("ssh-keygen -R <host>", "Fixes REMOTE HOST IDENTIFICATION HAS CHANGED"),
      c("ssh-add --apple-use-keychain ~/.ssh/id_ed25519", "Fixes being asked for your SSH passphrase every time", mac),
      c("rm -rf .next", "Fixes stale pages and odd Next.js build errors"),
      c("npx svelte-kit sync", "Fixes Cannot find module './$types'"),
      c("npx react-native start --reset-cache", "Fixes Unable to resolve module in Metro after installing a package"),
      c("cd ios && pod install --repo-update", "Fixes CocoaPods could not find compatible versions", mac),
      c('echo "sdk.dir=$HOME/Library/Android/sdk" > android/local.properties', "Fixes SDK location not found", mac),
      c("export JAVA_HOME=$(/usr/libexec/java_home -v 17)", "Fixes Gradle Unsupported class file major version, by switching JDK", mac),
      c("xcode-select --install", "Fixes xcrun: error: invalid active developer path after a macOS update", mac),
      c("sudo xcodebuild -license accept", "Fixes You have not agreed to the Xcode license agreements", mac),
      c("xattr -cr /Applications/<app>.app", "Fixes app is damaged and can't be opened", mac),
      c("sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder", "Fixes a domain that still resolves to an old IP", mac),
      c("python -m pip install <pkg>", "Fixes ModuleNotFoundError when pip installed into a different Python"),
      c("python3 -m venv .venv && source .venv/bin/activate", "Fixes externally-managed-environment errors from pip"),
      c("docker system prune -a", "Fixes no space left on device in Docker", danger),
      c("sudo usermod -aG docker $USER", "Fixes permission denied on the Docker socket", linux),
      c("kubectl logs <pod> --previous", "Finds why a pod is stuck in CrashLoopBackOff"),
      c("Set-ExecutionPolicy -Scope CurrentUser RemoteSigned", "Fixes running scripts is disabled on this system", windows),
    ],
  },
];

export const TOTAL_COMMANDS = COMMAND_SECTIONS.reduce((n, s) => n + s.entries.length, 0);

export const MAX_QUERY_LENGTH = 200;

export interface CommandHit {
  entry: CommandEntry;
  score: number;
}

export interface SectionResult {
  section: CommandSection;
  hits: CommandHit[];
}

/** The OS an entry is limited to, inherited from its section when not set. */
export function platformOf(entry: CommandEntry, section: CommandSection): CommandPlatform | undefined {
  return entry.platform ?? section.platform;
}

function scoreTerm(term: string, entry: CommandEntry, section: CommandSection): number {
  const cmd = entry.cmd.toLowerCase();
  if (cmd === term) return 10;
  if (cmd.startsWith(term)) return 8;
  if (cmd.split(/[\s|&;=/]+/).some((w) => w.replace(/^-+/, "").startsWith(term))) return 6;
  if (cmd.includes(term)) return 5;
  if (entry.keywords?.some((k) => k.toLowerCase().includes(term))) return 4;
  if (entry.description.toLowerCase().includes(term)) return 3;
  if (section.title.toLowerCase().includes(term)) return 2;
  if (platformOf(entry, section)?.toLowerCase().includes(term)) return 2;
  if (section.keywords?.some((k) => k.toLowerCase().includes(term))) return 1;
  return 0;
}

/**
 * Filter sections by stack or section id, then by query. Every query term must
 * match somewhere (command, keywords, description, section title or section
 * keywords). With a query, hits are ranked within a section and sections are
 * ranked by their best hit; without one, the curated order is kept.
 */
export function searchCommands(query: string, filter: { stack?: CommandStack | null; sectionId?: string | null } = {}): SectionResult[] {
  const terms = query.slice(0, MAX_QUERY_LENGTH).trim().toLowerCase().split(/\s+/).filter(Boolean);
  const results: Array<SectionResult & { best: number; order: number }> = [];
  COMMAND_SECTIONS.forEach((section, order) => {
    if (filter.stack && section.stack !== filter.stack) return;
    if (filter.sectionId && section.id !== filter.sectionId) return;
    const hits: CommandHit[] = [];
    for (const entry of section.entries) {
      let score = 0;
      let matched = true;
      for (const term of terms) {
        const s = scoreTerm(term, entry, section);
        if (!s) {
          matched = false;
          break;
        }
        score += s;
      }
      if (matched) hits.push({ entry, score });
    }
    if (!hits.length) return;
    if (terms.length) hits.sort((a, b) => b.score - a.score);
    results.push({ section, hits, best: hits[0].score, order });
  });
  if (terms.length) results.sort((a, b) => b.best - a.best || a.order - b.order);
  return results.map(({ section, hits }) => ({ section, hits }));
}

/** Split a command into literal text and <placeholder> parts for rendering. */
export function splitPlaceholders(cmd: string): Array<{ text: string; placeholder: boolean }> {
  // split() with a capturing group puts the captured placeholders at odd indices.
  return cmd
    .split(PLACEHOLDER_RE)
    .map((text, i) => ({ text, placeholder: i % 2 === 1 }))
    .filter((part) => part.text.length > 0);
}
