#!/usr/bin/env node
/**
 * Stamps a fresh cache version into public/sw.js before every production
 * build (wired up as the npm "prebuild" script, which npm runs automatically
 * before "build"). This is what makes the service worker's caches versioned:
 * each deploy gets a new version, so `activate` drops the previous deploy's
 * caches instead of serving stale HTML/assets forever.
 */
import { writeFile } from "node:fs/promises";
import { execSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const outPath = path.join(root, "..", "public", "sw.js");

function resolveVersion() {
  if (process.env.VERCEL_GIT_COMMIT_SHA) return process.env.VERCEL_GIT_COMMIT_SHA.slice(0, 10);
  try {
    return execSync("git rev-parse --short HEAD", { cwd: root, stdio: ["ignore", "pipe", "ignore"] })
      .toString()
      .trim();
  } catch {
    return Date.now().toString(36);
  }
}

// The actual service worker logic. Kept inline (rather than a separate
// runtime source file) so there is exactly one place to edit the worker,
// and the version stamp below is the only thing that ever changes.
const SW_BODY = `
const ASSET_CACHE = \`devbox-assets-\${VERSION}\`;
const PAGE_CACHE = \`devbox-pages-\${VERSION}\`;
const OFFLINE_URL = "/offline";
const SHELL_URLS = ["/", OFFLINE_URL, "/manifest.webmanifest"];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(PAGE_CACHE)
      .then((cache) => cache.addAll(SHELL_URLS))
      .catch(() => {
        // Best-effort: offline support degrades gracefully if the shell
        // can't be precached (e.g. first install while already offline).
      }),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(
          names
            .filter((name) => name.startsWith("devbox-") && name !== ASSET_CACHE && name !== PAGE_CACHE)
            .map((name) => caches.delete(name)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

// The page (see service-worker-register.tsx) posts this once the user
// clicks "Update" in the update banner — we never skip waiting on our own,
// so an update never force-refreshes a page mid-use.
self.addEventListener("message", (event) => {
  if (event.data === "SKIP_WAITING") self.skipWaiting();
});

function isStaticAsset(url) {
  return (
    url.pathname.startsWith("/_next/static/") ||
    url.pathname.startsWith("/icons/") ||
    /\\.(?:png|jpg|jpeg|svg|webp|ico|woff2?)$/.test(url.pathname)
  );
}

// Only ever GET, same-origin requests are touched. DevBox has no API routes
// and no fetch() calls carrying tool input (JWTs, passwords, secrets, files
// all stay in page memory/DOM), so there is nothing user-entered to
// accidentally cache here — only the app shell and static build assets.
self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(PAGE_CACHE).then((cache) => cache.put(request, copy));
          return response;
        })
        .catch(() => caches.match(request).then((cached) => cached || caches.match(OFFLINE_URL))),
    );
    return;
  }

  if (isStaticAsset(url)) {
    event.respondWith(
      caches.match(request).then(
        (cached) =>
          cached ||
          fetch(request).then((response) => {
            const copy = response.clone();
            caches.open(ASSET_CACHE).then((cache) => cache.put(request, copy));
            return response;
          }),
      ),
    );
  }
});
`;

const version = resolveVersion();
const source = `// GENERATED FILE — do not edit by hand.
// Source: scripts/build-sw.mjs. Regenerated by the "prebuild" npm script.
const VERSION = ${JSON.stringify(version)};
${SW_BODY}`;

await writeFile(outPath, source);
console.log(`wrote public/sw.js (version ${version})`);
